Rename functions to mark as internal

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -1,7 +1,7 @@
 # syntax=docker/dockerfile:1
 
 ARG VARIANT=@gsd_baseimage@
-FROM ${VARIANT}
+FROM ${VARIANT} AS repackager
 
 ENV GEOSUPPORT_DISTDIR @geosupport_basedir@/repo
 ENV GEOSUPPORT_FULL_VERSION @geosupport_fullversion@
@@ -16,25 +16,70 @@ RUN set -ex; \
 
 COPY @gsd_dcp_distfile@ /geosupport.zip
 COPY geo_h.patch /geo_h.patch
-COPY geosupport.sh /geosupport.sh
 
 WORKDIR "${GEOSUPPORT_DISTDIR}"
 
 RUN set -eux; \
-    echo "Extracting zip file /geosupport.zip to ${GEOSUPPORT_DISTDIR} directory." && \
-    mkdir "version-${GEOSUPPORT_FULL_VERSION}" && \
-    unzip -qj /geosupport.zip "**/bin/c_client" -d "version-${GEOSUPPORT_FULL_VERSION}/bin" && \
-    unzip -qj /geosupport.zip "**/fls/*" -d "version-${GEOSUPPORT_FULL_VERSION}/fls" && \
-    unzip -qj /geosupport.zip "**/include/foruser/*" -d "version-${GEOSUPPORT_FULL_VERSION}/include" && \
-    unzip -qj /geosupport.zip "**/lib/*" -d "version-${GEOSUPPORT_FULL_VERSION}/lib" && \
-    chmod +x /geosupport.sh && \
-    mv /geosupport.sh "version-${GEOSUPPORT_FULL_VERSION}/bin/geosupport" && \
-    mv "version-${GEOSUPPORT_FULL_VERSION}/bin/c_client" "version-${GEOSUPPORT_FULL_VERSION}/bin/goat" && \
-    mv "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h" "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h.orig" && \
-    patch -i /geo_h.patch -o "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h" "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h.orig" && \
-    tar czvf "geosupport-${GEOSUPPORT_FULL_VERSION}.tgz" "version-${GEOSUPPORT_FULL_VERSION}" && \
-    rm -rf "version-${GEOSUPPORT_FULL_VERSION}" && \
-    rm /geosupport.zip && \
-    rm /geo_h.patch
+        \
+        echo "Extracting zip file /geosupport.zip to ${GEOSUPPORT_DISTDIR} directory."; \
+        mkdir "version-${GEOSUPPORT_FULL_VERSION}"; \
+        unzip -qj /geosupport.zip "**/bin/c_client" -d "version-${GEOSUPPORT_FULL_VERSION}/bin"; \
+        unzip -qj /geosupport.zip "**/fls/*" -d "version-${GEOSUPPORT_FULL_VERSION}/fls"; \
+        unzip -qj /geosupport.zip "**/include/foruser/*" -d "version-${GEOSUPPORT_FULL_VERSION}/include"; \
+        unzip -qj /geosupport.zip "**/lib/*" -d "version-${GEOSUPPORT_FULL_VERSION}/lib"; \
+        mv "version-${GEOSUPPORT_FULL_VERSION}/bin/c_client" "version-${GEOSUPPORT_FULL_VERSION}/bin/goat"; \
+        mv "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h" "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h.orig"; \
+        patch -i /geo_h.patch -o "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h" "version-${GEOSUPPORT_FULL_VERSION}/include/geo.h.orig"; \
+        tar czvf "geosupport-${GEOSUPPORT_FULL_VERSION}.tgz" "version-${GEOSUPPORT_FULL_VERSION}"; \
+        rm -rf "version-${GEOSUPPORT_FULL_VERSION}"; \
+        rm /geosupport.zip; \
+        rm /geo_h.patch;
 
 VOLUME "${GEOSUPPORT_DISTDIR}"
+
+ARG VARIANT=@gsd_baseimage@
+FROM ${VARIANT} AS installer
+
+ENV GEOSUPPORT_BASEDIR="${GEOSUPPORT_BASEDIR:-@geosupport_basedir@}"
+ENV GEOSUPPORT_DISTDIR="${GEOSUPPORT_DISTDIR:-@geosupport_basedir@/repo}"
+ENV GEOSUPPORT_FULL_VERSION @geosupport_fullversion@
+ENV GEOSUPPORT_HOME="${GEOSUPPORT_HOME:-${GEOSUPPORT_BASEDIR}/current}"
+ENV GEOFILES="${GEOFILES:-${GEOSUPPORT_HOME}/fls/}"
+ENV GS_LIBRARY_PATH="${GS_LIBRARY_PATH:-${GEOSUPPORT_HOME}/lib}"
+ENV GS_INCLUDE_PATH="${GS_INCLUDE_PATH:-${GEOSUPPORT_HOME}/include}"
+
+ENV LANG C.UTF-8
+
+COPY --from=repackager "${GEOSUPPORT_DISTDIR}/geosupport-${GEOSUPPORT_FULL_VERSION}.tgz" /geosupport.tgz
+
+RUN set -eux; \
+        \
+        mkdir -p "${GEOSUPPORT_BASEDIR}"; \
+        cd "${GEOSUPPORT_BASEDIR}"; \
+        tar xzvf /geosupport.tgz; \
+        ln -s "version-${GEOSUPPORT_FULL_VERSION}" "${GEOSUPPORT_HOME}"; \
+        rm /geosupport.tgz; \
+        echo "${GS_LIBRARY_PATH}" > /etc/ld.so.conf.d/geosupport.conf; \
+        ldconfig; \
+        initenvf="${GEOSUPPORT_HOME}/bin/initenv"; \
+        { \
+# TODO Clean up generated initenv file: include ldconfig logic here?
+            echo '#!/usr/bin/env bash'; \
+            echo 'set -Eeuo pipefail'; \
+            echo "export GEOSUPPORT_HOME=${GEOSUPPORT_HOME}"; \
+            echo "export GEOFILES=${GEOSUPPORT_HOME}/fls/"; \
+            echo "export GEOSUPPORT_=${}"; \
+            echo "export GEOSUPPORT_=${}"; \
+            echo "export GS_LIBRARY_PATH=${GS_LIBRARY_PATH}"; \
+            echo "export GS_INCLUDE_PATH=${GS_INCLUDE_PATH}"; \
+            echo "export PATH=${GEOSUPPORT_HOME}/bin:\$PATH"; \
+        } > "${initenvf}"; \
+        chmod +x "${initenvf}";
+
+ENV PATH ${GEOSUPPORT_HOME}/bin:$PATH
+
+COPY geosupport.sh "${GEOSUPPORT_BASEDIR}/version-${GEOSUPPORT_FULL_VERSION}/bin/geosupport.sh"
+
+RUN set -eux; \
+        \
+        chmod +x "${GEOSUPPORT_BASEDIR}/version-${GEOSUPPORT_FULL_VERSION}/bin/geosupport.sh";
