Fix for issue #10.
But I mean it this time...
See https://github.com/mlipper/geosupport-docker/issues/10

diff --git a/templates/custombasedir.sh.template b/templates/custombasedir.sh.template
--- a/templates/custombasedir.sh.template
+++ b/templates/custombasedir.sh.template
@@ -81,10 +81,12 @@ main() {
                 die "Invalid option: $1"; shift
                 ;;
             *)
-                compress; shift
+                echo "Ignoring unkown argument: $1"; shift
                 ;;
         esac
     done
+    compress \
+        || die "Could not compress the Geosupport distribution with CUSTOMDIR=${CUSTOMDIR}."
 }
 
 show() {
