WIP: refine scripting

diff --git a/templates/geosupport.sh.template b/templates/geosupport.sh.template
--- a/templates/geosupport.sh.template
+++ b/templates/geosupport.sh.template
@@ -12,19 +12,6 @@ cd "${this_dir}"
 #
 
 declare -a commands
-declare -a switches
-declare -A props
-
-#
-# Environment
-#
-
-export GEOSUPPORT_FULL_VERSION="@geosupport_fullversion@"
-export GEOSUPPORT_BASEDIR="${GEOSUPPORT_BASEDIR:-@geosupport_basedir@}"
-export GEOSUPPORT_HOME="${GEOSUPPORT_HOME:-${GEOSUPPORT_BASEDIR}/current}"
-export GEOFILES="${GEOFILES:-${GEOSUPPORT_HOME}/fls/}"
-export GS_LIBRARY_PATH="${GS_LIBRARY_PATH:-${GEOSUPPORT_HOME}/lib}"
-export GS_INCLUDE_PATH="${GS_INCLUDE_PATH:-${GEOSUPPORT_HOME}/include}"
 
 #
 # Functions
@@ -33,144 +20,6 @@ export GS_INCLUDE_PATH="${GS_INCLUDE_PATH:-${GEOSUPPORT_HOME}/include}"
 die() {
     echo "$*" 1>&2
     exit 1
-}
-
-_install_files() {
-    local cdir="$(pwd)"
-    mkdir -p ${GEOSUPPORT_BASEDIR} \
-        && cd ${GEOSUPPORT_BASEDIR} \
-        && tar xzvf ${GEOSUPPORT_DISTFILE} \
-        && ln -svL ${GEOSUPPORT_FULL_VERSION} ${GEOSUPPORT_HOME}
-    cd "${cdir}"
-}
-
-#
-# Configures how the Geosupport shared library files are located by ld
-# at runtime.
-#
-# By default, Geosupport libs are visible to the dynamic linker by
-# symlinking all $GEOSUPPORT_HOME/lib/*.so files into /usr/local/lib
-# and running ldconfig.
-# 
-# There are two other, mutually exclusive options to achieve the
-# same goal. Source this file with one of the following flags:
-#
-#   --ldlibpath    The LD_LIBRARY_PATH environment variable will
-#                  set/updated with $GEOSUPPORT_HOME/lib
-#
-#   --ldconfig     Creates file /etc/ld.so.conf.d/geosupport.conf
-#                  containing the expanded value of $GEOSUPPORT_HOME/lib
-#
-_configure_so_path() {
-    local ldconfig=
-    local ldlibpath=
-    for s in ${switches}; do
-        case "${s}" in
-            ldconfig)
-                ldconfig="true"
-                ;;
-            ldlibpath)
-                ldlibpath="true"
-                ;;
-            *)
-                continue
-                ;;
-        esac
-    done
-    if [ -n "${ldconfig}" ]; then
-        # Add GS_LIBRARY_PATH to the system runtime shared library path using ldconfig.
-        # This usually requires superuser (root) privileges.
-        echo "${GS_LIBRARY_PATH}" > /etc/ld.so.conf.d/geosupport.conf
-        ldconfig
-        #echo "Result of \$GS_LIBRARY_PATH > /etc/ld.so.conf.d/geosupport.conf after calling ldconfig:"
-        #echo "$(ldconfig -p | grep -i ${GS_LIBRARY_PATH})"
-    else
-        # Add GS_LIBRARY_PATH to the LD_LIBRARY_PATH
-        if [ -n "${ldlibpath}" ]; then
-            [[ "$LD_LIBRARY_PATH" =~ "${GS_LIBRARY_PATH}" ]] || \
-                export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${GS_LIBRARY_PATH}
-            #echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
-        fi # End ldlibpath
-    fi # End ldconfig
-}
-
-#
-# Adds $GEOSUPPORT/bin to the PATH if it's not already there.
-#
-# TODO Make persistent?
-#      echo "${GEOSUPPORT_HOME}/bin" >> $HOME/.profile
-#        or
-#      echo "${GEOSUPPORT_HOME}/bin" > /etc/profile.d/geosupport.sh
-#
-_configure_path() {
-    [[ "$PATH" =~ "${GEOSUPPORT_HOME}/bin" ]] || \
-        export PATH="${GEOSUPPORT_HOME}/bin:${PATH}"
-}
-
-#
-# This function does three things:
-#
-# 1. Unpack the Geosupport distribution using the givem version
-#    information.
-#
-# 2. Register Geosupport's shared libraries with the dynamic linker
-#    so that they may be loaded at runtime.
-#
-# 3. Add the directory containing this script to system path.
-#
-# Task 1 is implemented by function _install_files.
-# Task 2 is implemented by function _configure_so_path.
-# Task 3 is implemented by function _configure_path.
-#
-# See the comments of each function for information on defaults and
-# options.
-#
-_install() {
-    [[ "$#" -eq 1 ]] || die "createln: 1 directory name argument required, $# given";
-    _install_files
-    _configure_so_path
-    _configure_path
-}
-
-_createln() {
-    [[ "$#" -eq 1 ]] || die "_createln: 1 directory name argument required, $# given";
-    dname="$1"
-    cd "${GEOSUPPORT_HOME}/${dname}";
-    for f in *.so; do
-        ln -svL "$PWD/$f" "/usr/local/${dname}/$f";
-    done;
-}
-
-_removeln() {
-    [ "$#" -eq 1 ] || die "_removeln: 1 directory name argument required, $# given";
-    dname="$1"
-    cd "${GEOSUPPORT_HOME}/${dname}";
-    for f in *.so; do
-        rm "/usr/local/${dname}/$f";
-    done;
-}
-
-#
-# Write and eval the geosupport.env file
-#
-# Switches:
-#   --release
-#   --patch
-#   --major
-#   --minor
-#
-_setenv() {
-    local envf="${this_dir}/geosupport.env"
-    rm -f "${envf}"
-    tee "${envf}" <<-EOS
-export GEOSUPPORT_FULL_VERSION="@geosupport_fullversion@"
-export GEOSUPPORT_BASEDIR="${GEOSUPPORT_BASEDIR:-@geosupport_basedir@}"
-export GEOSUPPORT_HOME="${GEOSUPPORT_HOME:-${GEOSUPPORT_BASEDIR}/current}"
-export GEOFILES="${GEOFILES:-${GEOSUPPORT_HOME}/fls/}"
-export GS_LIBRARY_PATH="${GS_LIBRARY_PATH:-${GEOSUPPORT_HOME}/lib}"
-export GS_INCLUDE_PATH="${GS_INCLUDE_PATH:-${GEOSUPPORT_HOME}/include}"
-
-EOS
 }
 
 usage() {
@@ -190,28 +39,26 @@ Commands:
 
   help          Show this usage message and exit.
 
-  install       Install Geosupport binaries, libraries and data.
-
-                Options:
-
-                  --ldconfig    Permanently adds GS_LIBRARY_PATH to the
-                                runtime shared library path.
-
-                                NOTE: Use of this option causes '--ldlibpath'
-                                to be ignored if it also appears on the
-                                command line.
-
-                                NOTE: Requires root privileges
-
-                  --ldlibpath   Adds GS_LIBRARY_PATH to the LD_LIBRARY_PATH
-                                variable.
-
-                                NOTE: This option will be ignored if
-                                '--ldconfig' also appears on the command line.
+  install       Create soft links for Geosupport binaries and shared libs
+                under /usr/local/bin and /usr/local/lib respectively.
+                After shared libraries are symlinked, ldconfig is called
+                to update the ld cache.
 
   version       Print Geosupport release and version information.
 
 EOF
+}
+
+_createln() {
+    [[ "$#" -gt 1 ]] || die "$0: directory and 1 or more file names required.";
+    dname="$1"
+    shift
+    cd "/usr/local/${dname}"
+    for f in "$@"; do
+        echo "creating link /usr/local/${dname}/${f} -> ${GEOSUPPORT_HOME}/${dname}/${f}";
+        ln -svL  "${GEOSUPPORT_HOME}/${dname}/${f}" "${f}";
+    done;
+    cd "${this_dir}"
 }
 
 _env() {
@@ -233,8 +80,16 @@ _goat() {
     "${GEOSUPPORT_HOME}/bin/goat"
 }
 
+_install() {
+    _createln 'bin' 'geosupport'
+    local sofiles=$(ls -1 $GEOSUPPORT_HOME/lib/*.so | xargs basename -s $GEOSUPPORT_HOME | tr '\n' ' ')
+    _createln 'lib' ${sofiles[$@]}
+    ldconfig
+}
+
 _version() {
 cat <<- EOF
+# @gsd_buildtimestamp@
 
 Geosupport @geosupport_fullversion@
 -----------------------------------
@@ -250,6 +105,10 @@ Geosupport @geosupport_fullversion@
 Geosupport is written and maintained by the NYC Department of City Planning.
 https://www1.nyc.gov/site/planning/data-maps/open-data.page#geocoding_application
 
+
+geosupport-docker @gsd_version@
+-------------------------------
+
 This Geosupport distribution was generated using the geosupport-docker project
 by Matthew Lipper.
 https://github.com/mlipper/geosupport-docker
@@ -258,7 +117,6 @@ https://hub.docker.com/r/mlipper/geosupport-docker
 
 EOF
 }
-
 
 main() {
 
@@ -269,7 +127,7 @@ main() {
             -e | environment)
                 commands+=( "environment" ); shift
                 ;;
-            goat)
+            -g | goat)
                 commands+=( "goat" ); shift
                 ;;
             -h | help)
@@ -278,17 +136,8 @@ main() {
             -i | install)
                 commands+=( "install" ); shift
                 ;;
-            -p | path)
-                commands+=( "path" ); shift
-                ;;
-            -s | sopath)
-                commands+=( "sopath" ); shift
-                ;;
             -v | version)
                 commands+=( "version" ); shift
-                ;;
-            --*)
-                switches+=( "$1" ); shift
                 ;;
             *)
                 die "Invalid argument: $1"; shift
@@ -306,10 +155,6 @@ main() {
                 usage ;;
             install)
                 _install ;;
-            path)
-                _configure_path ;;
-            sopath)
-                _configure_so_path ;;
             version)
                 _version ;;
             *)
